- charts:
  - clusters:
    - amazon-cluster
    configuration:
      values:
        image: bitnami/rabbitmq:3.6.8-r0
        persistence:
          accessMode: ReadWriteOnce
          enabled: true
          size: 8Gi
        rabbitmqManagerPort: 15672
        rabbitmqNodeName: rabbit
        rabbitmqNodePort: 5672
        rabbitmqNodeType: stats
        rabbitmqUsername: user
        rabbitmqVhost: /
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
    name: rabbitmq
    src: https://github.com/kuberlab-catalog/rabbitmq/
    version: 0.4.5
  name: rabbit
- charts:
  - clusters:
    - amazon-cluster
    configuration:
      values:
        image: kuberlab/mnist-ui:latest
        mnist_mlapp: mnist-deep
        mnist_model: mnist-deep-build-3
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        serviceType: ClusterIP
    name: mnist-ui
    src: https://github.com/kuberlab-catalog/mnist-ui/
    version: 1.0.0
  name: mnist-ui
